version: 2.1

commands:
  install_node_13_deb:
    description: "Install Node 13"
    steps:
      - run: sudo apt -y update && sudo apt -y upgrade
      - run: curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
      - run: sudo apt-get install -y nodejs


jobs:
  build-frontend:
    docker:
      - image: cimg/base:2021.05-18.04
    steps:
      - checkout
      - install_node_13_deb
      # - restore_cache:
      #     keys: [frontend-build]
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          keys: frontend-build

  build-backend:
    docker:
      - image: cimg/base:2021.05-18.04
    steps:
      - checkout
      - install_node_13_deb
      # - restore_cache:
      #     keys: [backend-build]
      - run:
          name: Build backend
          command: |
            cd backend
            npm install
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          keys: backend-build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend          